<?php

$mapping = [
    'AmoCRM\ModelException'             => __DIR__ . '/vendor/dotzero/amocrm/src/ModelException.php',
    'AmoCRM\Models\Widgets'             => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Widgets.php',
    'AmoCRM\Models\Transaction'         => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Transaction.php',
    'AmoCRM\Models\Catalog'             => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Catalog.php',
    'AmoCRM\Models\Unsorted'            => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Unsorted.php',
    'AmoCRM\Models\Note'                => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Note.php',
    'AmoCRM\Models\Webhooks'            => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Webhooks.php',
    'AmoCRM\Models\AbstractModel'       => __DIR__ . '/vendor/dotzero/amocrm/src/Models/AbstractModel.php',
    'AmoCRM\Models\Account'             => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Account.php',
    'AmoCRM\Models\CatalogElement'      => __DIR__ . '/vendor/dotzero/amocrm/src/Models/CatalogElement.php',
    'AmoCRM\Models\Task'                => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Task.php',
    'AmoCRM\Models\Contact'             => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Contact.php',
    'AmoCRM\Models\Customer'            => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Customer.php',
    'AmoCRM\Models\Company'             => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Company.php',
    'AmoCRM\Models\ModelInterface'      => __DIR__ . '/vendor/dotzero/amocrm/src/Models/ModelInterface.php',
    'AmoCRM\Models\Call'                => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Call.php',
    'AmoCRM\Models\CustomersPeriods'    => __DIR__ . '/vendor/dotzero/amocrm/src/Models/CustomersPeriods.php',
    'AmoCRM\Models\CustomField'         => __DIR__ . '/vendor/dotzero/amocrm/src/Models/CustomField.php',
    'AmoCRM\Models\Lead'                => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Lead.php',
    'AmoCRM\Models\Links'               => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Links.php',
    'AmoCRM\Models\Pipelines'           => __DIR__ . '/vendor/dotzero/amocrm/src/Models/Pipelines.php',
    'AmoCRM\NetworkException'           => __DIR__ . '/vendor/dotzero/amocrm/src/NetworkException.php',
    'AmoCRM\Request\Request'            => __DIR__ . '/vendor/dotzero/amocrm/src/Request/Request.php',
    'AmoCRM\Request\ParamsBag'          => __DIR__ . '/vendor/dotzero/amocrm/src/Request/ParamsBag.php',
    'AmoCRM\Webhooks\Listener'          => __DIR__ . '/vendor/dotzero/amocrm/src/Webhooks/Listener.php',
    'AmoCRM\Exception'                  => __DIR__ . '/vendor/dotzero/amocrm/src/Exception.php',
    'AmoCRM\Helpers\Fields'             => __DIR__ . '/vendor/dotzero/amocrm/src/Helpers/Fields.php',
    'AmoCRM\Helpers\B2BFamily'          => __DIR__ . '/vendor/dotzero/amocrm/src/Helpers/B2BFamily.php',
    'AmoCRM\Helpers\B2BFamilyException' => __DIR__ . '/vendor/dotzero/amocrm/src/Helpers/B2BFamilyException.php',
    'AmoCRM\Client'                     => __DIR__ . '/vendor/dotzero/amocrm/src/Client.php',
    
    'Monolog\ErrorHandler' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/ErrorHandler.php',
    'Monolog\Logger'       => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Logger.php',
    'Monolog\Registry'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Registry.php',
    
    'Monolog\Formatter\ChromePHPFormatter'   => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/ChromePHPFormatter.php',
    'Monolog\Formatter\ElasticaFormatter'    => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/ElasticaFormatter.php',
    'Monolog\Formatter\FlowdockFormatter'    => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/FlowdockFormatter.php',
    'Monolog\Formatter\FluentdFormatter'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/FluentdFormatter.php',
    'Monolog\Formatter\FormatterInterface'   => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/FormatterInterface.php',
    'Monolog\Formatter\GelfMessageFormatter' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/GelfMessageFormatter.php',
    'Monolog\Formatter\HtmlFormatter'        => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/HtmlFormatter.php',
    'Monolog\Formatter\JsonFormatter'        => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/JsonFormatter.php',
    'Monolog\Formatter\LineFormatter'        => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php',
    'Monolog\Formatter\LogglyFormatter'      => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/LogglyFormatter.php',
    'Monolog\Formatter\LogstashFormatter'    => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/LogstashFormatter.php',
    'Monolog\Formatter\MongoDBFormatter'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/MongoDBFormatter.php',
    'Monolog\Formatter\NormalizerFormatter'  => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php',
    'Monolog\Formatter\ScalarFormatter'      => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/ScalarFormatter.php',
    'Monolog\Formatter\WildfireFormatter'    => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Formatter/WildfireFormatter.php',
    
    'Monolog\Handler\AbstractHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php',
    'Monolog\Handler\AbstractProcessingHandler' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php',
    'Monolog\Handler\AbstractSyslogHandler'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/AbstractSyslogHandler.php',
    'Monolog\Handler\AmqpHandler'               => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/AmqpHandler.php',
    'Monolog\Handler\BrowserConsoleHandler'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/BrowserConsoleHandler.php',
    'Monolog\Handler\BufferHandler'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/BufferHandler.php',
    'Monolog\Handler\ChromePHPHandler'          => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/ChromePHPHandler.php',
    'Monolog\Handler\CouchDBHandler'            => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/CouchDBHandler.php',
    'Monolog\Handler\CubeHandler'               => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/CubeHandler.php',
    'Monolog\Handler\DeduplicationHandler'      => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/DeduplicationHandler.php',
    'Monolog\Handler\DoctrineCouchDBHandler'    => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/DoctrineCouchDBHandler.php',
    'Monolog\Handler\DynamoDbHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/DynamoDbHandler.php',
    'Monolog\Handler\ElasticSearchHandler'      => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/ElasticSearchHandler.php',
    'Monolog\Handler\ErrorLogHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/ErrorLogHandler.php',
    'Monolog\Handler\FilterHandler'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FilterHandler.php',
    'Monolog\Handler\FingersCrossedHandler'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossedHandler.php',
    'Monolog\Handler\FirePHPHandler'            => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FirePHPHandler.php',
    'Monolog\Handler\FleepHookHandler'          => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FleepHookHandler.php',
    'Monolog\Handler\FlowdockHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FlowdockHandler.php',
    'Monolog\Handler\GelfHandler'               => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/GelfHandler.php',
    'Monolog\Handler\GroupHandler'              => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/GroupHandler.php',
    'Monolog\Handler\HandlerInterface'          => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/HandlerInterface.php',
    'Monolog\Handler\HandlerWrapper'            => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/HandlerWrapper.php',
    'Monolog\Handler\HipChatHandler'            => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/HipChatHandler.php',
    'Monolog\Handler\IFTTTHandler'              => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/IFTTTHandler.php',
    'Monolog\Handler\LogEntriesHandler'         => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/LogEntriesHandler.php',
    'Monolog\Handler\LogglyHandler'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/LogglyHandler.php',
    'Monolog\Handler\MailHandler'               => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/MailHandler.php',
    'Monolog\Handler\MandrillHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/MandrillHandler.php',
    'Monolog\Handler\MissingExtensionException' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/MissingExtensionException.php',
    'Monolog\Handler\MongoDBHandler'            => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/MongoDBHandler.php',
    'Monolog\Handler\NativeMailerHandler'       => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/NativeMailerHandler.php',
    'Monolog\Handler\NewRelicHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/NewRelicHandler.php',
    'Monolog\Handler\NullHandler'               => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/NullHandler.php',
    'Monolog\Handler\PHPConsoleHandler'         => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/PHPConsoleHandler.php',
    'Monolog\Handler\PsrHandler'                => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/PsrHandler.php',
    'Monolog\Handler\PushoverHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/PushoverHandler.php',
    'Monolog\Handler\RavenHandler'              => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/RavenHandler.php',
    'Monolog\Handler\RedisHandler'              => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/RedisHandler.php',
    'Monolog\Handler\RollbarHandler'            => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/RollbarHandler.php',
    'Monolog\Handler\RotatingFileHandler'       => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php',
    'Monolog\Handler\SamplingHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SamplingHandler.php',
    'Monolog\Handler\SlackbotHandler'           => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SlackbotHandler.php',
    'Monolog\Handler\SlackHandler'              => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SlackHandler.php',
    'Monolog\Handler\SlackWebhookHandler'       => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SlackWebhookHandler.php',
    'Monolog\Handler\SocketHandler'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php',
    'Monolog\Handler\StreamHandler'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php',
    'Monolog\Handler\SwiftMailerHandler'        => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SwiftMailerHandler.php',
    'Monolog\Handler\SyslogHandler'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SyslogHandler.php',
    'Monolog\Handler\SyslogUdpHandler'          => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdpHandler.php',
    'Monolog\Handler\TestHandler'               => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/TestHandler.php',
    'Monolog\Handler\WhatFailureGroupHandler'   => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/WhatFailureGroupHandler.php',
    'Monolog\Handler\ZendMonitorHandler'        => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/ZendMonitorHandler.php',
    'Monolog\Handler\Curl\Util'                 => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/Curl/Util.php',
    
    'Monolog\Handler\FingersCrossed\ActivationStrategyInterface'    =>
        __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossed/ActivationStrategyInterface.php',
    'Monolog\Handler\FingersCrossed\ChannelLevelActivationStrategy' =>
        __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossed/ChannelLevelActivationStrategy.php',
    'Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy'   =>
        __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/FingersCrossed/ErrorLevelActivationStrategy.php',
    
    'Monolog\Handler\Slack\SlackRecord' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/Slack/SlackRecord.php',
    
    'Monolog\Handler\SyslogUdp\UdpSocket' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php',
    
    'Monolog\Processor\GitProcessor'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/GitProcessor.php',
    'Monolog\Processor\IntrospectionProcessor'   => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/IntrospectionProcessor.php',
    'Monolog\Processor\MemoryPeakUsageProcessor' => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/MemoryPeakUsageProcessor.php',
    'Monolog\Processor\MemoryProcessor'          => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/MemoryProcessor.php',
    'Monolog\Processor\MemoryUsageProcessor'     => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/MemoryUsageProcessor.php',
    'Monolog\Processor\MercurialProcessor'       => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/MercurialProcessor.php',
    'Monolog\Processor\ProcessIdProcessor'       => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/ProcessIdProcessor.php',
    'Monolog\Processor\PsrLogMessageProcessor'   => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/PsrLogMessageProcessor.php',
    'Monolog\Processor\TagProcessor'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/TagProcessor.php',
    'Monolog\Processor\UidProcessor'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/UidProcessor.php',
    'Monolog\Processor\WebProcessor'             => __DIR__ . '/vendor/monolog/monolog/src/Monolog/Processor/WebProcessor.php',
    
    'Psr\Log\AbstractLogger'           => __DIR__ . '/vendor/psr/log/Psr/Log/AbstractLogger.php',
    'Psr\Log\InvalidArgumentException' => __DIR__ . '/vendor/psr/log/Psr/Log/InvalidArgumentException.php',
    'Psr\Log\LoggerAwareInterface'     => __DIR__ . '/vendor/psr/log/Psr/Log/LoggerAwareInterface.php',
    'Psr\Log\LoggerAwareTrait'         => __DIR__ . '/vendor/psr/log/Psr/Log/LoggerAwareTrait.php',
    'Psr\Log\LoggerInterface'          => __DIR__ . '/vendor/psr/log/Psr/Log/LoggerInterface.php',
    'Psr\Log\LoggerTrait'              => __DIR__ . '/vendor/psr/log/Psr/Log/LoggerTrait.php',
    'Psr\Log\LogLevel'                 => __DIR__ . '/vendor/psr/log/Psr/Log/LogLevel.php',
    'Psr\Log\NullLogger'               => __DIR__ . '/vendor/psr/log/Psr/Log/NullLogger.php',
    
    'AmoPRO\AmoPRO' => __DIR__ . '/app/AmoPRO.php',
    'AmoPRO\Config' => __DIR__ . '/app/Config.php',
    'AmoPRO\Logger' => __DIR__ . '/app/Logger.php',
    'AmoPRO\Order'  => __DIR__ . '/app/Order.php',
    
    'AmoPRO\Core\App'                   => __DIR__ . '/app/Core/App.php',
    'AmoPRO\Core\AccountTrait'          => __DIR__ . '/app/Core/AccountTrait.php',
    'AmoPRO\Core\CommentTrait'          => __DIR__ . '/app/Core/CommentTrait.php',
    'AmoPRO\Core\ContactTrait'          => __DIR__ . '/app/Core/ContactTrait.php',
    'AmoPRO\Core\CustomFieldsTrait'     => __DIR__ . '/app/Core/CustomFieldsTrait.php',
    'AmoPRO\Core\LeadTrait'              => __DIR__ . '/app/Core/LeadTrait.php',
    'AmoPRO\Core\TaskTrait'              => __DIR__ . '/app/Core/TaskTrait.php',
    'AmoPRO\Core\UsersTrait'             => __DIR__ . '/app/Core/UsersTrait.php',
    'AmoPRO\Exceptions\BaseException'    => __DIR__ . '/app/Exceptions/BaseException.php',
    'AmoPRO\Exceptions\ConfigException'  => __DIR__ . '/app/Exceptions/ConfigException.php',
    'AmoPRO\Exceptions\FieldsException'  => __DIR__ . '/app/Exceptions/FieldsException.php',
    'AmoPRO\Exceptions\LibraryException' => __DIR__ . '/app/Exceptions/LibraryException.php',
    'AmoPRO\Exceptions\OrderException'   => __DIR__ . '/app/Exceptions/OrderException.php',

];

spl_autoload_register(function ($class) use ($mapping) {
    if (isset($mapping[$class])) {
        require $mapping[$class];
    }
}, true);


__HALT_COMPILER(); ?>
